class_name Enums

enum ZLayer {
	NPC_BEHIND_ROOM_DEEP = -150,
	NPC_BEHIND_ROOM_CONTENT = -50,
	ROOM_CONTENT_BACK = -10,
	ROOM_CONTENT_DEFAULT = 0,
	ROOM_CONTENT_FRONT = 10,
	NPC_DEFAULT = 0,
	PUDDLE = 100,
	DEBUG_OVERLAY = 1000,
}
